apiVersion: batch/v1
kind: CronJob
metadata:
  name: auto-import-job
  namespace: firefly
spec:
  schedule: "0 18 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: data-importer-cli
              image: fireflyiii/data-importer:latest-cli@sha256:607bce54c02ffbfe909f29a5287e2df3477c681ea210e33100c08e4ed131a1d5
              command: ["php", "artisan", "importer:import", "/import/import-config.json"]
              envFrom:
                - secretRef:
                    name: firefly-config
              env:
                - name: FIREFLY_III_URL
                  value: http://firefly-iii-chart:80
                - name: WEB_SERVER
                  value: "false"
                - name: IGNORE_DUPLICATE_ERRORS
                  value: "true"
              volumeMounts:
                - name: bank-imports
                  mountPath: /import
          volumes:
            - name: bank-imports
              secret:
                secretName: bank-imports
                items:
                  - key: import-config.json
                    path: import-config.json
