apiVersion: batch/v1
kind: CronJob
metadata:
  name: auto-import-job
  namespace: firefly
spec:
  schedule: "0 18 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: data-importer-cli
              image: fireflyiii/data-importer:latest-cli@sha256:15e75ad7b57ee797b0fa8621868ebf457a10068cda07ca10decf61dcf62f57e5
              envFrom:
                - secretRef:
                    name: firefly-config
              env:
                - name: FIREFLY_III_URL
                  value: http://firefly-iii-chart:80
                - name: WEB_SERVER
                  value: "false"
              volumeMounts:
                - name: bank-imports
                  mountPath: /import
          volumes:
            - name: bank-imports
              secret:
                secretName: bank-imports
                items:
                  - key: bank-import-1.json
                    path: bank-import-1.json
                  - key: bank-import-2.json
                    path: bank-import-2.json
                  - key: bank-import-3.json
                    path: bank-import-3.json
