apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: importer-chart
  namespace: firefly
spec:
  source:
    helm:
      valuesObject:
        fireflyiii:
          url: http://firefly-iii-chart:80
          vanityUrl: https://firefly-iii.tail9a43.ts.net
          auth:
            existingSecret: firefly-config
        config:
          existingSecret: firefly-config
          files: {}
          env:
            IGNORE_DUPLICATE_ERRORS: "false"
            TZ: "Europe/Paris"
        # persistence:
        #   storageClassName: app-config
        ingress:
          enabled: true
          className: tailscale
          hosts:
            - firefly-importer
          tls:
            - hosts:
                - firefly-importer
        additionalVolumes:
          - name: bank-imports
            secret:
              secretName: bank-imports
              items:
                - key: bank-import-1.json
                  path: bank-import-1.json
                - key: bank-import-2.json
                  path: bank-import-2.json
                - key: bank-import-3.json
                  path: bank-import-3.json
        additionalVolumeMounts:
          - name: bank-imports
            mountPath: /var/www/html/storage/configurations
