apiVersion: v1
kind: Secret
metadata:
  name: dev-env-authorized-keys
  namespace: dev-env
stringData:
  # Key filename must match the SSH username (thomas).
  # sshd_config: AuthorizedKeysFile /etc/ssh/authorized_keys/%u
  thomas: |
    ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICMH/yRpnGAezra+JiVyyK9h1Z9X3xyRxOILZkYZSEbC thomas@t480s-bluefin
