apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: syncthing-thomas-helm-chart
  namespace: nextcloud
spec:
  project: nextcloud
  source:
    repoURL: oci.trueforge.org/truecharts
    targetRevision: 22.x
    chart: syncthing
    helm:
      valuesObject:
        persistence:
          config:
            enabled: true
            mountPath: "/var/syncthing"
            type: pvc
            existingClaim: syncthing-thomas-data
        ingress:
          main:
            enabled: true
            ingressClassName: tailscale
            targetSelector:
              main: main
            hosts:
              - host: syncthing-thomas
                paths:
                  - path: /
                    pathType: Prefix
            tls:
              - hosts:
                  - syncthing-thomas
  destination:
    server: https://kubernetes.default.svc
    namespace: nextcloud
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
