apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-syncthing-thomas
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: evora.lan
    path: "/export/syncthing/thomas" # Replace with your exported NFS path
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: syncthing-thomas-data
spec:
  volumeName: nfs-pv-syncthing-thomas
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: "" # Empty string for pre-provisioned volumes
