apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trilium
  namespace: argocd
spec:
  project: trilium
  source:
    repoURL: https://triliumnext.github.io/helm-charts
    chart: trilium
    targetRevision: 1.3.x
  destination:
    server: https://kubernetes.default.svc
    namespace: trilium
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
      - CreateNamespace=true
