apiVersion: v1
kind: Namespace
metadata:
  name: actual-budget
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: actual-budget
  namespace: argocd
spec:
  sourceRepos:
    - https://github.com/roukydesbois/homelab
    - https://community-charts.github.io/helm-charts

  sourceNamespaces:
    - actual-budget

  destinations:
    - namespace: actual-budget
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:
    - group: ""
      kind: PersistentVolumeClaim
    - group: ""
      kind: PersistentVolume

  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: actual-budget
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: actual-budget
  project: actual-budget
  source:
    repoURL: https://github.com/roukydesbois/homelab
    targetRevision: main
    path: kustomize/actual-budget/overlays/thomelab
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
