apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: keycloak
  project: keycloak
  source:
    repoURL: https://github.com/roukydesbois/homelab
    targetRevision: main
    path: kustomize/keycloak-bitnami/overlays/thomelab
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

