apiVersion: v1
kind: Namespace
metadata:
  name: dev-env

---

apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: dev-env
  namespace: argocd
spec:
  sourceRepos:
    - https://github.com/roukydesbois/homelab
  sourceNamespaces:
    - dev-env
  destinations:
    - namespace: dev-env
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: PersistentVolumeClaim
    - group: ""
      kind: PersistentVolume
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-env
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: dev-env
  project: dev-env
  source:
    repoURL: https://github.com/roukydesbois/homelab
    targetRevision: main
    path: kustomize/dev-env/overlays/thomelab
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
      - ServerSideApply=true
