apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: fedora
spec:
  runStrategy: Always
  template:
    spec:
      domain:
        devices:
          disks:
          - disk:
              bus: virtio
            name: containerdisk
          - disk:
              bus: virtio
            name: cloudinit
          rng: {}
        features:
          acpi: {}
          smm:
            enabled: true
        firmware:
          bootloader:
            efi:
              secureBoot: true
        resources:
          requests:
            memory: 1Gi
      terminationGracePeriodSeconds: 180
      volumes:
      - containerDisk:
          image: quay.io/containerdisks/fedora:43
        name: containerdisk
      - cloudInitNoCloud:
          userData: |-
            #cloud-config
            # The default username is: fedora
            ssh_authorized_keys:
              - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICMH/yRpnGAezra+JiVyyK9h1Z9X3xyRxOILZkYZSEbC thomas@t480s-bluefin
        name: cloudinit
---
apiVersion: v1
kind: Service
metadata:
  name: fedora-ssh
  annotations:
    tailscale.com/expose: "true"
spec:
  selector:
    kubevirt.io/domain: fedora
  ports:
    - port: 22
      targetPort: 22
      protocol: TCP
