---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gluetun-env
  namespace: thomflix
spec:
  encryptedData:
    env: AgBy++Pm/Jz4d4Bb1U40AO0J2FzsTJ5W3TfPuaSF3/xjo6OKYAJ748O0aDMKC4ISZWul1WBzTg6YrdzJH4dsAfPMK+94ycInoExzv//LQppgj1Si3xsOOQ/PYVqmuJ/bcU5ffu6Xq9rb+jJQyyFxq2wQhtJi6EsKm4bLeD+Z/F8+6LHY4EFSEir0dyFU8+jx0Umh53Hpq2ScSel4IyhY7NI2GyFSF3L5p1wMJGnFOku0pgL/KZbvtzso6gqrxcKszaaLA2hgG3ro+Gey5JC4clkJa4JIFreKCf4gUojribDMr+kwijRxgat4tqtOgIR+Rr3yWMw8jN8UDZMyL1uSOY4Zvr4dedXmv9cLr4a6H8QdYTlNSR1Nvt6TxCNfuqXB/fXYtPHC6Mt1POXKXgh38SuTQ3NwBdmbvY1Yj2XrV2R/GpeUAhDrwbYyzgMHeKhRKtNf8x2CouVSU1/+uKqxLSiPVnkGPd5VnEYB5qsZA05aVCIW5I1hw6VVUVNYsuiFep3GCADuDPpMgCrCAYjyU9RCZGR31LXL6OLqjafLHAE6qFs+NxHk6StuRRXURzpkSILV1+3VXCJHL3P3BYaSXY+rTb1DojE5+ldp6BWHbaj3prTu2bJRW3SamK8sxcAolZZIJWg7lYPrQybYL7DNgqEJXaRTj54RINky3BhIdTdIZp6nP+HUDTUJ94lvEOyoG6/dSAHGNEp6iIqzMnE4GRmQiwBVRqt/89R4K4ozSDc6vnW4PTgLEOivoer/e/0LeJ4ySGKRHQgvzq+uqN4baKM9Uzu0rUGOaqX6GoCi5PLGMF0K5+nVuuh/bIaJc8j3IH1iuGUpDBbrjRl9pxM8kRNk9tBnX0TFUmCQyDFdzjEPWR5lyusLjk6mzpl/RdFT/YszLUUTuF0a7i3625ob3lCY6eYCGXNXQeumhYuQM+8dCJ8/KYWaQ73r3tVCoUnANnjiUyugpucfavzIHxYYSl9D9OQdKqBrGjquwOgdBVoDd/vplzr0KLNfA5jCT6wydoojy9KoB56wN6sVpaavTfiyM9FAGaIG+VFqMem8OXcLnDfAYfzElkWKEliVJ4cK55UCoXG5RfB676w+Zhe7A5cv
  template:
    metadata:
      creationTimestamp: null
      name: gluetun-env
      namespace: thomflix
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-reader
  namespace: thomflix
rules:
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["gluetun-env"]  # Limit to specific secret for better security
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gitops-secret-reader
  namespace: thomflix
subjects:
- kind: ServiceAccount
  name: default
  namespace: thomflix
roleRef:
  kind: Role
  name: secret-reader
  apiGroup: rbac.authorization.k8s.io
