apiVersion: v1
kind: Namespace
metadata:
  name: hedgedoc
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: hedgedoc
  namespace: argocd
spec:
  sourceRepos:
    - https://github.com/roukydesbois/homelab
  sourceNamespaces:
    - hedgedoc
  destinations:
    - namespace: hedgedoc
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: storage.k8s.io
      kind: StorageClass
    - group: ""
      kind: PersistentVolumeClaim
    - group: ""
      kind: PersistentVolume
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hedgedoc
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: hedgedoc
  project: hedgedoc
  source:
    repoURL: https://github.com/roukydesbois/homelab
    targetRevision: main
    path: kustomize/hedgedoc/overlays/thomelab
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
