apiVersion: v1
kind: Namespace
metadata:
  name: immich
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: immich
  namespace: argocd
spec:
  sourceRepos:
    - https://github.com/roukydesbois/homelab
    - https://immich-app.github.io/immich-charts
  sourceNamespaces:
    - immich
  destinations:
    - namespace: immich
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: storage.k8s.io
      kind: StorageClass
    - group: ""
      kind: PersistentVolumeClaim
    - group: ""
      kind: PersistentVolume
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: immich
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: immich
  project: immich
  source:
    repoURL: https://github.com/roukydesbois/homelab
    targetRevision: immich-debug
    path: kustomize/immich/overlays/thomelab
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
