apiVersion: v1
kind: Namespace
metadata:
  name: keycloak
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: keycloak
  namespace: argocd
spec:
  sourceRepos:
    - https://github.com/roukydesbois/homelab
    - registry-1.docker.io/bitnamicharts
  sourceNamespaces:
    - keycloak
  destinations:
    - namespace: keycloak
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: storage.k8s.io
      kind: StorageClass
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: keycloak
  project: keycloak
  source:
    repoURL: https://github.com/roukydesbois/homelab
    targetRevision: main
    path: kustomize/keycloak-bitnami/overlays/thomelab
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
