apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - keycloak-app-of-apps.yaml
  - immich-app-of-apps.yaml
  - gluetun-env-sealed.yaml
  - thomflix-app-of-apps.yaml

#patches:
#  - patch: |-
#      apiVersion: argoproj.io/v1alpha1
#      kind: Application
#      metadata:
#        name: argocd
#        namespace: argocd
#      spec:
#        source:
#          helm:
#            valuesObject:
#              configs:
#                params:
#                  application.namespaces: "keycloak,immich,thomflix"
#    target:
#      group: argoproj.io
#      version: v1alpha1
#      kind: Application
#      name: argocd
#      namespace: argocd
