apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - keycloak-app-of-apps.yaml
  - immich-app-of-apps.yaml
  - thomflix-app-of-apps.yaml
  - nextcloud-app-of-apps.yaml
  - firefly-app-of-apps.yaml
  - protonmailbridge-app-of-apps.yaml
  - hedgedoc-app-of-apps.yaml
  - paperless-app-of-apps.yaml
  - renovate-app-of-apps.yaml
#  - trillium-app-of-apps.yaml
#patches:
#  - patch: |-
#      - op: add
#        path: /metadata/annotations
#        value:
#          notifications.argoproj.io/subscribe.on-sync-succeeded.ntfy: ""
#          notifications.argoproj.io/subscribe.on-sync-failed.ntfy: ""
#          notifications.argoproj.io/subscribe.on-health-degraded.ntfy: ""
#    target:
#      kind: Application
#patches:
#  - patch: |-
#      apiVersion: argoproj.io/v1alpha1
#      kind: Application
#      metadata:
#        name: argocd
#        namespace: argocd
#      spec:
#        source:
#          helm:
#            valuesObject:
#              configs:
#                params:
#                  application.namespaces: "keycloak,immich,thomflix"
#    target:
#      group: argoproj.io
#      version: v1alpha1
#      kind: Application
#      name: argocd
#      namespace: argocd
