apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - keycloak-app-of-apps.yaml
  - immich-app-of-apps.yaml
  - thomflix-app-of-apps.yaml

patches:
  - patch: |-
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: argocd-cmd-params-cm
        namespace: argocd
      data:
        application.namespaces: keycloak,immich,thomflix
    target:
      kind: ConfigMap
      name: argocd-cmd-params-cm
