apiVersion: v1
kind: Namespace
metadata:
  name: n8n
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: n8n
  namespace: argocd
spec:
  sourceRepos:
    - https://github.com/roukydesbois/homelab
    - https://community-charts.github.io/helm-charts
  sourceNamespaces:
    - n8n
  destinations:
    - namespace: n8n
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: storage.k8s.io
      kind: StorageClass
    - group: ""
      kind: PersistentVolumeClaim
    - group: ""
      kind: PersistentVolume
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: n8n
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: n8n
  project: n8n
  source:
    repoURL: https://github.com/roukydesbois/homelab
    targetRevision: main
    path: kustomize/n8n/overlays/thomelab
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
