apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-immich-test
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.100.210 
    path: "/export/immich-new"
