apiVersion: v1
kind: Namespace
metadata:
  name: nextcloud
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: nextcloud
  namespace: argocd
spec:
  sourceRepos:
    - https://github.com/roukydesbois/homelab
    - https://nextcloud.github.io/helm
    - tccr.io/truecharts
  sourceNamespaces:
    - nextcloud
  destinations:
    - namespace: nextcloud
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: storage.k8s.io
      kind: StorageClass
    - group: ""
      kind: PersistentVolumeClaim
    - group: ""
      kind: PersistentVolume
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nextcloud
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: nextcloud
  project: nextcloud
  source:
    repoURL: https://github.com/roukydesbois/homelab
    targetRevision: main
    path: kustomize/nextcloud/overlays/thomelab
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
