apiVersion: v1
kind: Namespace
metadata:
  name: thomflix
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: thomflix
  namespace: argocd
spec:
  sourceRepos:
    - https://github.com/roukydesbois/homelab
    - tccr.io/truecharts
  sourceNamespaces:
    - thomflix
  destinations:
    - namespace: thomflix
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: storage.k8s.io
      kind: StorageClass
    - group: ""
      kind: PersistentVolumeClaim
    - group: ""
      kind: PersistentVolume
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: thomflix
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: thomflix
  project: thomflix
  source:
    repoURL: https://github.com/roukydesbois/homelab
    targetRevision: main
    path: kustomize/thomflix/overlays/thomelab
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
