apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-database
spec:
  instances: 3

  # imageName will be patched via kustomization

  storage:
    size: 8Gi
    storageClass: cnpg-storage-class
  postgresql:
    shared_preload_libraries:
      - "vchord.so"
    enableAlterSystem: true

  startDelay: 30
  stopDelay: 100
