apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-database
spec:
  instances: 3

  # imageName will be patched via kustomization

  storage:
    size: 8Gi
    storageClass: cnpg-storage-class
  postgresql:
    shared_preload_libraries:
      - "vchord.so"
    enableAlterSystem: true

  startDelay: 30
  stopDelay: 100

  # Bootstrap from existing immich-pg cluster using pg_basebackup
  bootstrap:
    pg_basebackup:
      source: immich-pg-source

  # Run SQL after bootstrap to migrate from vectors to vchord extension
  postBootstrapSQL:
    # Drop old vectors extension and related objects
    - DROP EXTENSION IF EXISTS vectors CASCADE;
    # Create new vchord extension
    - CREATE EXTENSION IF NOT EXISTS vchord CASCADE;
    - CREATE EXTENSION IF NOT EXISTS earthdistance CASCADE;
    # Ensure proper ownership and permissions
    # - ALTER SCHEMA vectors OWNER TO immich;
    - GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA vectors TO app;
    - GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO app;

  # Reference to source cluster for bootstrap
  externalClusters:
    - name: immich-pg-source
      connectionParameters:
        host: immich-pg-rw
        user: immich
        dbname: immich
      password:
        name: immich-pg-app
        key: password
