apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-library
spec:
  volumeName: nfs-pv-immich-test
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  storageClassName: "" # Empty string for pre-provisioned volumes
