apiVersion: k8s.keycloak.org/v2alpha1
kind: KeycloakRealmImport
metadata:
  name: self-hosted-apps-realm
  namespace: keycloak
spec:
  keycloakCRName: keycloak
  realm:
    # The realm JSON is stored in the keycloak-realm-import secret
    # We'll reference it using a secret reference
    id: self-hosted-apps
    realm: self-hosted-apps
    enabled: true
