# ArgoCD Application to deploy actual-budget Helm chart
# This application is deployed in the actual-budget namespace and project
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: actual-budget-helm-chart
  namespace: actual-budget
spec:
  project: actual-budget
  source:
    repoURL: https://community-charts.github.io/helm-charts
    targetRevision: 1.8.x
    chart: actualbudget
    helm:
      releaseName: actual-budget
      valuesObject:
        strategy:
          type: Recreate
  destination:
    server: https://kubernetes.default.svc
    namespace: actual-budget
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
