apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - dbCluster.yaml
  - odoo-data.yaml
  - ../../../base/odoo

patches:
  - path: odoo-helm-values.yaml

# namespace: odoo-v2