apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grist-data
  namespace: grist
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 20Gi
