apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: intel-device-plugins-operator
  namespace: argocd
spec:
  source:
    helm:
      valuesObject:
        manager:
          devices:
            gpu: true
