---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: velero
  namespace: velero
spec:
  encryptedData:
    cloud: AgBJso3DlThbFc7OjeM8gyyJmOv3ULD7l2uIZKnxeGueakCEDbFR+oTNeY7QG7wuLWau17cwC7DYMiyRDepgMbGAk6gihhoKmdwYzHK8ML9XP3JJn6ghvallemyvvehHN2jWcNBsHwL/CHiDwBov1pt1UZwuwANq9H0lIbFc0vFQIr+y95rIHDVJYEoOtdgRtXZzRBW0NaFfsoslfStx4F9oWuzjEWAdEqjZ2LjGyhVFe3Xo13NGK3/zB1tR4h1iHBdYUao/8es4BZujT6KMiMoC44hXkhbb6cNlrgaH1cxwu+RO8dRLPaSlxVzMExJze612Lib5K0yWea/Vno7ua0hkEST6QUK+JLYwA7vH4kvfp8Z5i+lDbRVME6ZdwEy0DmXc5ce7A2SLlmTQSgDFeS0dzrUFAkBNm4OwROvRwWOMMMC77jp8ZQ6R5kb3FXNCPGGjVr8YNd/5HffpCu7Aom1yQ7LcTW2U+VbMHjAbRhRYziBW/vmAeOwhd9+8PS9Nabq0GkscyQlzpIvcgH1rXSuMfkZ5jMLHU2cJ3NZZiGfyAxp5VRaU1FDjL5ltGSFeKyZPYeXS0GAGTDHCmfA/U8+wpjjzfw1ZjVdVUD/SeXfGxFcVEyzkq6l3p956O/4caNhz7IvAqwyUVnbcoe4AfD2ztkrMd+r+emzxUMHU20NEUVut7tESHHrkRO8lp268Y+KdllEjaqZJEx5W1bzc5XotuSB3W2ukMVfUpuAMhraNNsfUhDorMx448cOiDRjghLv/iPwgaN0nOhc9cKGYT6LGacI71ZUkquIj+qui+rtl4kagMRFv222nUQzyCHWNKFnd+AzF5e2aNaKd4HkgZE61LNigH/8TFb8rnprxCUr2NjNnVkp97ThkwO9454hk
  template:
    metadata:
      creationTimestamp: null
      name: velero
      namespace: velero
