---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: credentials-velero
  namespace: velero
spec:
  encryptedData:
    cloud: AgAJgc7BBK6/UEENb3g9rDwQgQErFONtkgeDk4yQMdxi/4nEcRXxL3bFyq66dgPv83ALZJiwmqR30kY+yhyl5Slxx9/es89ANcQPq471wJzSklizSpc9SbzCyEp+nd86US1jklmFrfjmKhq7OBlF2VMcx6+QIBCNIOR46TSPUpGSaQbvEFu57MHZA8ccwVaf0YDMDZrc3/y0GLJsY2dRobqvcJOIrS/dlwLmhjdAzkGJBLfp6GVE9VyeMSp3qGZ2i/ITvvzYBM81q9IlB+QP9Dc6wLHtiufcF4KB0CEcynYGrdQ4+wuqm2aBxsdl1OudejgOrtBD2Ad+X6GFnRn0ES8zVEsRJ0MbW+YzKYpbD8WY+4md8DMk0OexQyoNOy9bIta1ICGTAQzuw8Y1ooPm2EdGR53I5GWRmKGKB6YyMhMzxqbGDMjpUY/RdW/qwJvcWMrjt8tYNm/EOj8QTV7eC5rs+hsqwcXgMX3gkwTjFZ9PUeysPXOEyqhtfCFzHlAJ5g2XSvEmTcSPdhSn5inIs5rfx280lE8kMPSzArl1P/BZbNLQP07OphCQTsQ5Lg/mrE+Bl07dl+T2zmAdvrB9bOM04bqEeukRsnS9SkALQPc7LkR12ZBy5QUXEe4d2ArVrFNxA6H+8tyzXxclPpb41/cGZtmuk+YVwM/0CAZAJub+XDoMzrvsfz/2qBtnJSZKKiAF+PsjkOMMN1KABabvzxhmoQlDk5sHcGPzCNSw+61r4ubHKvl6BD8qyr4ZdeXRQ9XQsiKoqQ2G5D8sDUDoqQ42oTor/Ix0icgU8A+KPFKSLtfWM9WAJUaQd6cn4sy3NdVShzbScJct5Krevht9mR8B/9LIPkKTNnj3HHhSL3pUr1cUJYJCnnVnJ4sR0Qy1
  template:
    metadata:
      creationTimestamp: null
      name: credentials-velero
      namespace: velero
