---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: velero
  namespace: velero
spec:
  encryptedData:
    cloud: AgAs2uncxKpF8DfMyRKyvPLzw8p14x8QaHaw+2xEaSrNi7R4SauNBX8EbNtZepsKGuycAt1ut1iz0w9juE/LvsnIBKMKoSZ+DhH92T9Lz94EzsQw0SkHqxxTPcvPAPkhZpmGSOsvvSB0119F1NcTA+sWejzttlmKk6+KQwK5vTc2i5uq3fm6VRE/7xYsxkW6zb1q+kRBRVhzeTtdzd1ZUZv5eDMegcIh9NEfeBG/mme43x+MqBB7IrHF80Y1YYY08J8np54XnVWCvtVi+Mua9JDbTyK/SfqRwoAh4OwUpT5xdf/xu4z49mbDlCe9TiQU0Oh1k3WMVzLN3kcwVnLyzHqaS3YaRFkayTojiykEcnYQNoDRD9U2Uc8NKPSszMyw2bIFVHrH5gu74/lR9S6sX+v3Mx/7h6TdIzxQuWH84JkQgsocylQJP6X36o7grcjUmQIfDMgoGSF6nReh9KAPXOUlOX39GPgg4G6oJtxrBCn+BWVfiQDoi39gX57o177QdD0J5wvjrGd9piJ74PMaScJT8f5nlDjdjQj4cwGnBhlJMS5TxccIZVtUPStd5SRwl6cuva1W9KEhPYGvhhnSt64MJvnf+owOmWoKWq2RK4RgmXXkrh8ikCHw7VdisQKwPoq5trMgqMLyOuMvGkHzATNxj9qVlzBqGkuoIfuRlHGdPQLPnO/jENNJ6Kf9d/hPVctF1lRdehLDbdFXYc3D0WGYiuoayMRG7lCQRnzzNRj2UtR5VIFZBX2OD22Fbs4GKT5JcXlZld64izj9wmAMmtzbSicLRfZBzXqTNAoI66QNbPO4tl0+QWNSElpsxJf1CNQFYj9dGgEEBsxO6RfKBwEp
  template:
    metadata:
      annotations:
        meta.helm.sh/release-name: velero
        meta.helm.sh/release-namespace: velero
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: velero
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: velero
        helm.sh/chart: velero-9.0.4
      name: velero
      namespace: velero
    type: Opaque
