apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tailscale-operator
  namespace: argocd
spec:
  source:
    helm:
      valuesObject:
        operatorConfig:
          hostname: thomelab-operator
