apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: nextcloud
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destinations:
    - namespace: nextcloud
      server: https://kubernetes.default.svc
    - namespace: argocd
      server: https://kubernetes.default.svc
  sourceRepos:
    - https://nextcloud.github.io/helm/
    - https://github.com/roukydesbois/homelab.git