apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: protonmail-bridge-sc
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Retain
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "2"
  fromBackup: ""
  fsType: "ext4"
  dataLocality: "disabled"
