---
- name: Update servers
  hosts: sbcs
  become: yes

  tasks:
    - name: Update apt packages
      apt:
        update_cache: yes
        upgrade: dist
        autoremove: yes
        autoclean: yes
        when: update_methods is defined and 'apt' in update_methods
