apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.37.0 (HEAD)
  labels:
    io.kompose.service: gotenberg
  name: gotenberg
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: gotenberg
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.37.0 (HEAD)
      labels:
        io.kompose.service: gotenberg
    spec:
      containers:
        # renovate: datasource=docker depName=docker.io/gotenberg/gotenberg
        - args:
            - gotenberg
            - --chromium-disable-javascript=true
            - --chromium-allow-list=file:///tmp/.*
          image: docker.io/gotenberg/gotenberg:8.31@sha256:f0d86e8a1dbc7b33a5a65cb251d02bb271a48ffa989da3feb5ed7d954fe4d4b3
          name: gotenberg
      restartPolicy: Always
