apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jackett
  namespace: thomflix
  labels:
    needs-config: yes 
spec:
  project: thomflix
  source:
    repoURL: "tccr.io/truecharts"
    chart: jackett
    targetRevision: 23.x
  destination:
    server: https://kubernetes.default.svc
    namespace: thomflix
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
