apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jellyfin
  namespace: thomflix
spec:
  project: thomflix
  source:
    repoURL: "https://jellyfin.github.io/jellyfin-helm"
    chart: jellyfin
    targetRevision: 2.x
  destination:
    server: https://kubernetes.default.svc
    namespace: thomflix
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
