apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: radarr
  namespace: thomflix
  labels:
    needs-config: true 
    needs-media: true
spec:
  project: thomflix
  source:
    repoURL: "tccr.io/truecharts"
    chart: radarr
    targetRevision: 23.x
  destination:
    server: https://kubernetes.default.svc
    namespace: thomflix
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
