apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sonarr
  namespace: thomflix
  labels:
    update-config: yes
    add-thomflix-media: yes
spec:
  project: thomflix
  source:
    repoURL: "tccr.io/truecharts"
    chart: sonarr
    targetRevision: 23.x
    helm:
      valuesObject:
        metrics:
          main:
            enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: thomflix
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/template/spec/hostUsers
