apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - hedgedoc-config-sealed.yaml
  - hedgedoc-db-sc.yaml
  - hedgedoc-db.yaml
  - hedgedoc-ingress.yaml
  - ../../base

patches:
  - patch: |-
      - op: add
        path: /spec/tls
        value:
          - hosts:
              - doc
      # - op: add
      #   path: /metadata/annotations
      #   value:
      #     tailscale.com/funnel: "true"
    target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: ts-hedgedoc
      namespace: hedgedoc
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: CMD_DOMAIN
          valueFrom:
            secretKeyRef:
              name: hedgedoc-config
              key: CMD_DOMAIN
    target:
      group: apps
      version: v1
      kind: Deployment
      name: hedgedoc
      namespace: hedgedoc
