apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - hedgedoc-db-sc.yaml
  - hedgedoc-db.yaml
  - hedgedoc-ingress.yaml
  - ../../base

patches:
  - patch: |-
      - op: add
        path: /spec/tls
        value:
          - hosts:
              - doc
      # - op: add
      #   path: /metadata/annotations
      #   value:
      #     tailscale.com/funnel: "true"
    target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: ts-hedgedoc
      namespace: hedgedoc
