apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: firefly-db-chart
  namespace: firefly
spec:
  project: firefly
  source:
    repoURL: https://firefly-iii.github.io/kubernetes
    targetRevision: 0.x
    chart: firefly-db
  destination:
    server: https://kubernetes.default.svc
    namespace: firefly
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
