apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - trilium-data-sc.yaml
  - trilium-data-pvc.yaml
  - trilium-ingress.yaml

patches:
  - patch: |-
      - op: add
        path: /spec/source/helm
        value:
          valuesObject:
            controllers:
              main:
                containers:
                  trilium:
                    image:
                      repository: triliumnext/notes
                      tag: v0.98.1
                      pullPolicy: IfNotPresent
            persistence:
              enabled: true
              existingClaim: trilium-data-pvc
    target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: trilium-helm-chart
      namespace: trilium
