apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: trilium-data-pvc
  namespace: trilium
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: trilium-data-sc
