apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: trilium
  namespace: trilium
  annotations:
    tailscale.com/tags: "tag:k8s"
spec:
  defaultBackend:
    service:
      name: trilium-helm-chart
      port:
        name: http
  ingressClassName: tailscale
  tls:
    - hosts:
        - notes
