# Service to expose Jellyfin to the talinet
apiVersion: v1
kind: Service
metadata:
  name: external-jellyfin
  namespace: thomflix
spec:
  selector:
    app.kubernetes.io/instance: jellyfin
    app.kubernetes.io/name: jellyfin
  type: LoadBalancer
  loadBalancerClass: tailscale
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: http

