apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: transmission
spec:
  defaultBackend:
    service:
      name: transmission
      port:
        name: main
  ingressClassName: tailscale
  tls:
    - hosts:
        - thomflix-transmission
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jackett
spec:
  defaultBackend:
    service:
      name: jackett
      port:
        name: main
  ingressClassName: tailscale
  tls:
    - hosts:
        - thomflix-jackett
