apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base

patches:
  - patch: |-
      - op: add
        path: /spec/source/helm/valuesObject/persistence/type
        value: pvc
      - op: add
        path: /spec/source/helm/valuesObject/persistence/subPath
        value: /data/torrents
      - op:add
        path: /spec/source/helm/valuesObject/persistence/existingClaim
        value: thomflix-media
    target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: transmission
      namespace: thomflix
    
