apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - library-pvc.yaml
  - directory-creation-job.yaml
  - thomflix-config-sc.yaml
  - wg-conf-sealed-secret.yaml
  - gluetun-env-sealed.yaml
  - ../../base
  - ingresses.yaml

patches:
  - patch: |-
      - op: add
        path: /spec/source/helm
        value:
          valuesObject:
            persistence:
              config:
                enabled: true
                mountPath: "/config"
                type: pvc
                namespace: thomflix
                accessModes: ReadWriteOnce
                size: 100Mi
                storageClass: thomflix-config
                targetSelector:
                  main:
                    main: {}
              downloads:
                enabled: true
                mountPath: "/data/torrents"
                type: pvc 
                namespace: thomflix
                existingClaim: thomflix-media
                subPath: "data/torrents"
                targetSelector:
                  main:
                    main: {}
            addons:
              vpn:
                type: gluetun
                killSwitch: true
                excludedNetworks_IPv4:
                  - "10.244.0.0/16"
                  - "192.168.100.0/24"
                  - "192.168.42.69/32"
                excludedNetworks_IPv6: []
    target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: transmission
      namespace: thomflix

replacements:
  - source:
      kind: Secret
      name: gluetun-env
      fieldPath: data.env
    targets:
      - select:
          group: argoproj.io
          version: v1alpha1
          kind: Application
          name: transmission
          namespace: thomflix
        fieldPaths:
          - spec.source.helm.valuesObject.addons.vpn.env
        options:
          create: true

