apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - library-pvc.yaml
  - directory-creation-job.yaml
  - thomflix-config-sc.yaml
  - gluetun-env-sealed.yaml
  - ../../base
  - ingresses.yaml

patches:
  - patch: |-
      - op: add
        path: /spec/source/helm
        value:
          valuesObject:
            persistence:
              config:
                enabled: true
                mountPath: "/config"
                type: pvc
                namespace: thomflix
                accessModes: ReadWriteOnce
                size: 100Mi
                storageClass: thomflix-config
                targetSelector:
                  main:
                    main: {}
              downloads:
                enabled: true
                mountPath: "/data/torrents"
                type: pvc 
                namespace: thomflix
                existingClaim: thomflix-media
                subPath: "data/torrents"
                targetSelector:
                  main:
                    main: {}
            addons:
              vpn:
                type: gluetun
                killSwitch: true
                excludedNetworks_IPv4:
                  - "10.244.0.0/16"
                  - "192.168.100.0/24"
                  - "192.168.42.69/32"
                excludedNetworks_IPv6: []
                env:
                  - name: VPN_SERVICE_PROVIDER
                    value: custom
                  - name: VPN_TYPE
                    value: wireguard
                  - name: WIREGUARD_ENDPOINT_IP
                    valueFrom:
                      secretKeyRef:
                        name: gluetun-env
                        key: WIREGUARD_ENDPOINT_IP
                  - name: WIREGUARD_ENDPOINT_PORT
                    valueFrom:
                      secretKeyRef:
                        name: gluetun-env
                        key: WIREGUARD_ENDPOINT_PORT
                  - name: WIREGUARD_PUBLIC_KEY
                    valueFrom:
                      secretKeyRef:
                        name: gluetun-env
                        key: WIREGUARD_PUBLIC_KEY
                  - name: WIREGUARD_PRIVATE_KEY
                    valueFrom:
                      secretKeyRef:
                        name: gluetun-env
                        key: WIREGUARD_PRIVATE_KEY
                  - name: WIREGUARD_ADDRESSES
                    valueFrom:
                      secretKeyRef:
                        name: gluetun-env
                        key: WIREGUARD_ADDRESSES
    target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: transmission
      namespace: thomflix
