apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - thomflix-config-sc.yaml
  - thomflix-media-pvc.yaml
  - ../../base

patches:
  - patch: |-
      - op: add
        path: /spec/source/helm/valuesObject/persistence/config/type
        value: pvc
      - op:add
        path: /spec/source/helm/valuesObject/persistence/config/size
        value: 100Mi
      - op: add
        path: /spec/source/helm/valuesObject/persistence/config/storageClass
        value: thomflix-config-sc
      - op: add
        path: /spec/source/helm/valuesObject/persistence/config/retain
        value: true
    target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: transmission
      namespace: thomflix
    
