apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - library-pvc.yaml
  # - directory-creation-job.yaml
  - thomflix-config-sc.yaml
  - gluetun-env-sealed.yaml
  - ../../base
  - ingresses.yaml
  - external-jellyfin-service.yaml

patches:
  - path: patch-transmission.yaml
  - path: patch-add-thomflix-media.yaml
    target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      namespace: thomflix
      labelSelector: "add-thomflix-media=yes"
  - path: patch-update-config.yaml
    target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      namespace: thomflix
      labelSelector: "update-config=yes"
  - path: patch-jellyfin.yaml
  # - path: patch-homarr.yaml
  # - path: patch-tdarr.yaml
