apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - library-pvc.yaml
  - directory-creation-job.yaml
  - thomflix-config-sc.yaml
  - wg-conf-sealed-secret.yaml
  - ../../base
  - ingresses.yaml

patches:
  - patch: |-
      - op: add
        path: /spec/source/helm
        value:
          valuesObject:
            linuxserverWgImage:
              repository: lscr.io/linuxserver/wireguard
              tag: latest
              pullPolicy: IfNotPresent
            persistence:
              config:
                enabled: true
                mountPath: "/config"
                type: pvc
                namespace: thomflix
                accessModes: ReadWriteOnce
                size: 100Mi
                storageClass: thomflix-config
                targetSelector:
                  main:
                    main: {}
              downloads:
                enabled: true
                mountPath: "/data/torrents"
                type: pvc 
                namespace: thomflix
                existingClaim: thomflix-media
                subPath: "data/torrents"
                targetSelector:
                  main:
                    main: {}
              wgConf:
                enabled: true
                type: secret
                objectName: wg-conf
                mountPath: "/config/wg_confs"
                items:
                  - key: wg0.conf
                    path: wg0.conf
                targetSelector:
                  main:
                    vpn: {}
            workload:
              main:
                podSpec:
                  initContainers:
                    vpn:
                      enabled: true
                      type: init
                      imageSelector: linuxserverWgImage
                      securityContext:
                        privileged: true
                        capabilities:
                          add: ["NET_ADMIN", "SYS_MODULE"]
                      fixedEnv:
                        PUID: 1000
                        PGID: 1000
                        TZ: "Europe/Paris"
    target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: transmission
      namespace: thomflix
