apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jellyfin
spec:
  source:
    helm:
      valuesObject:
        persistence:
          config:
            storageClass: thomflix-config
          media:
            accessModes: ReadWriteMany
            existingClaim: thomflix-media
        securityContext:
          privileged: true
          capabilities:
            add:
              - SYS_RAWIO
        volumeMounts:
          - name: dev-dri
            mountPath: /dev/dri
        volumes:
          - name: dev-dri
            hostPath:
              path: /dev/dri
