apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-thomflix-media
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: evora.lan
    path: "/mnt/thomflix-media" # Replace with your exported NFS path
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: thomflix-media
spec:
  volumeName: nfs-pv-thomflix-media
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  storageClassName: "" # Empty string for pre-provisioned volumes
