apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: n8n-helm-chart
  namespace: n8n
spec:
  source:
    helm:
      valuesObject:
        # Disable internal PostgreSQL
        postgresql:
          enabled: false

        # Use external PostgreSQL
        externalPostgresql:
          host: n8n-database-rw
          database: n8n
          username: n8n
          port: 5432

        # Main node configuration
        main:
          persistence:
            enabled: true
            existingClaim: n8n-data

          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
