---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: n8n-encryption-key
  namespace: n8n
spec:
  encryptedData:
    N8N_ENCRYPTION_KEY: AgAKhXF5q+OOSUPeDC6sqj65X1YxLVZoi9+CdrzDYlR40mOdNzrVHZS1Trokiu0OUA/VaCGfTEk6Zf7S/mW9zyQES1CPsjxigYIHhQJvdTjHhmJFo2yQS64mQrcXlHQ9sASKmWzXC4uuXGRSfnN2kZn++t1VjtN1b/YdcM97I+PY0tkdHO2Yap15YHfPgbobqV5j8lhRY8JOPe1EufHEwjGJfXp8gWabA/whcmyFUrQSFrTt9wF8C1Ox6EnWtycoHCEmyAs0fVF6JjJKiPhZSkFc4Wa8GRaISPEkTqlt5rSSiNhF+HjT06WNXO/iNF2dwfri37xS6KPoZc+alIrUdp5xZBgH13BwJv6NwffKqdqs3L9bQTYalB7Ne+vuZ6lUq8F6FjCWQJdQBK39yvWsrgoI+bEi9MXlcOr5uLH4sTX9ZqP/I0sSIGYVwoYPWZnbzQx8g/RSqoW1SnmZt6XDQz8rpVnUlqTNs2JQcvtUtGquCKfWmUhq3yH5DOEZhry4dofYyk2iQD3VU7+Y3Nz3QvZc/X+jmhJY3bjPeGF2Qq9bTuprsqX2I3+NIqPjtS7O15e32oTgbQ+vF8SlhOfItWDq9biGH1O5RsGvkIsYWcI0xkg4hgwbLOcA8i5uPjE0NEtaan+p4/ZvcIeKI0lqZhwjn3TegyZCx2rTceLlG4lqe7XQivxfcWqYfoajqTHdvHn/nNYQfcuE1esyUCkkKldpFaUHXeTbcaZaUCFBFEZMENzMR1Oekn8U3uM=
  template:
    metadata:
      name: n8n-encryption-key
      namespace: n8n
