apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: n8n-helm-chart
  namespace: n8n
spec:
  source:
    helm:
      valuesObject:
        strategy:
          type: "Recreate"
          
        log:
          level: warn

        db:
          type: postgresdb
          
        externalPostgresql:
          host: n8n-database-rw
          database: n8n
          username: n8n
          port: 5432
          existingSecret: db-secret

        existingEncryptionKeySecret: n8n-encryption-key

        main:
          editorBaseUrl: "https://n8n.tail9a43.ts.net"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 512m
              memory: 512Mi
          count: 1
          persistence:
            enabled: true
            accessMode: ReadWriteOnce
            volumeName: "n8n-main-data"
            mountPath: "/home/node/.n8n"
            size: 10Gi

        worker:
          mode: queue

          waitMainNodeReady:
            enabled: true

          resources:
            requests:
              cpu: 1000m
              memory: 250Mi
            limits:
              cpu: 2000m
              memory: 2Gi
          count: 1
          persistence:
            enabled: true
            accessMode: ReadWriteOnce
            volumeName: "n8n-worker-data"
            mountPath: "/home/node/.n8n"
            size: 5Gi
              
        redis:
          enabled: true

        ingress:
          enabled: true
          className: tailscale
          hosts:
            - host: n8n
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - hosts:
                - n8n
