apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: n8n-helm-chart
  namespace: n8n
spec:
  source:
    helm:
      valuesObject:
        # Disable internal PostgreSQL
        postgresql:
          enabled: false

        # Configure database type
        db:
          type: postgresdb
          postgresdb:
            ssl:
              enabled: false

        # Main node configuration
        main:
          # Persistence configuration using existing PVC
          persistence:
            enabled: true
            existingClaim: n8n-data

          # Resource limits and requests
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "1Gi"
              cpu: "1000m"

          # Database connection via environment variables
          extraEnv:
            - name: DB_TYPE
              value: "postgresdb"
            - name: DB_POSTGRESDB_HOST
              valueFrom:
                secretKeyRef:
                  name: n8n-database-app
                  key: host
            - name: DB_POSTGRESDB_PORT
              valueFrom:
                secretKeyRef:
                  name: n8n-database-app
                  key: port
            - name: DB_POSTGRESDB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: n8n-database-app
                  key: dbname
            - name: DB_POSTGRESDB_USER
              valueFrom:
                secretKeyRef:
                  name: n8n-database-app
                  key: username
            - name: DB_POSTGRESDB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: n8n-database-app
                  key: password
