apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: n8n-helm-chart
  namespace: n8n
spec:
  source:
    helm:
      valuesObject:
        # Disable internal PostgreSQL
        postgresql:
          enabled: false

        # Use external PostgreSQL
        externalPostgresql:
          host: "" # Will be set via extraEnv
          database: n8n
          username: n8n
          password: "" # Will be set via extraEnv
          port: 5432

        # Main node configuration
        main:
          persistence:
            enabled: true
            existingClaim: n8n-data

          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "1Gi"
              cpu: "1000m"

          # Database connection via environment variables
          env:
            DB_TYPE: "postgresdb"
            DB_POSTGRESDB_HOST:
              valueFrom:
                secretKeyRef:
                  name: n8n-database-app
                  key: host
            DB_POSTGRESDB_PORT:
              valueFrom:
                secretKeyRef:
                  name: n8n-database-app
                  key: port
            DB_POSTGRESDB_DATABASE:
              valueFrom:
                secretKeyRef:
                  name: n8n-database-app
                  key: dbname
            DB_POSTGRESDB_USER:
              valueFrom:
                secretKeyRef:
                  name: n8n-database-app
                  key: username
            DB_POSTGRESDB_PASSWORD:
              valueFrom:
                secretKeyRef:
                  name: n8n-database-app
                  key: password
