apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-nextcloud
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: evora.lan
    path: "/data/nextcloud" # Replace with your exported NFS path
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-data
spec:
  volumeName: nfs-pv-nextcloud
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: "" # Empty string for pre-provisioned volumes
