apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nextcloud-helm-chart
  namespace: nextcloud
spec:
  project: nextcloud
  source:
    repoURL: https://nextcloud.github.io/helm
    targetRevision: 6.x
    chart: nextcloud
  destination:
    server: https://kubernetes.default.svc
    namespace: nextcloud
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
