apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nextcloud
  namespace: nextcloud-test
spec:
  project: nextcloud-test
  source:
    repoURL: https://nextcloud.github.io/helm/
    chart: nextcloud
    targetRevision: 8.x
    helm:
      releaseName: nextcloud
  destination:
    server: https://kubernetes.default.svc
    namespace: nextcloud-test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
      - CreateNamespace=true