---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: paperless-keycloak-config-secret
  namespace: paperless
spec:
  encryptedData:
    PAPERLESS_SOCIALACCOUNT_PROVIDERS: AgAsvvgACVQOuip+LdtJX3XI5gqYia/+g21jMcNDZJ7/BMIXTIXpatoRihddZNAOZwowlfGkXnlKfx/0kTo1JM3D/N4+NyLIfRYhnUZwOfFfwPR/eXKzq9/fROnNGSCLw6xSjWz1Dh/j8TEDd3JxayYods+jQW9xwYbv+Lvl8Xs2F9Tn0IL0wdP6DisAw/0E/DP9EhG1ECWV6jlM3ZlAkyxczQLW1wsl9u7OqGmSaV8XF/JW6OIaHQww5YWamlcbZVbhFB5llB7CFQyZ+04IPRA3Wl2H8Ih1fItj3QV7hDtBZVYsOCPg8ygPSubf+2JcBlCy9pk9iipAPA4YYuqvaeq4PY1KDmSndZH6Cvd1sPsB2xtUtug1PYQ7GaOTvg/DsvJibr7qcmkbesKBdOKrjd0sjzMgsJG3kjMSo5fYyroSpctVLM2J3i+pSc5nxjaktyX0C6s1fFiH+RAtSSlgmfEtqHwJcOPeuwsXtLHSPobwihtCW7VKIuPpagNCFcpwGWd+//3Tlkt6SgRp+ijFkZTkBMrMERIcHqwt+OpSY3Jv7VsTnAjqfoKT2SDloBVahUJKLjQd9YFU1QptQhJ55NpnUCkAH19P11+sE8ps9USgbLZU9zTWw3dQR2Mq9NKIze2UnM+E6H56QaAd6oPYvJr0ooxEy3UOwjhd4hiMa26l+axnH9MjDOwuHg9MfxHlEoO5S9lx5FbB/+37e0P0nFCPDbVX92O99k3eu6dgjm2wI+CvbpFkcxG43LLRE1IGLMid6n5epepkbVFo82oeCWPmwIf9aspcfGdHmbiqVBPZ52lxDGew1xM19r5n0JVfMBzNYa/nu+XRvEKqQjzuojN2vesj4y/HT93L7YAI1cUCRyF3RCQOpN1aiNPS82TpEtxNSM6SPelDdsze8iYso4FnRwyTcjJkWoFXHKdNY3qJqOBaA6wcgeGIr/lT7LFq3YT2jvun+xSuDSE/QphQiNuxY5keRfoVIf7OzBddwJ1xsrYrRHwC4LXlgwTTXNn30Z+5txCUs5SPt7zb5jwT27JNQKA5oYBJ6XcoV7295Tf6oWv+plMCp7vrNHkZzbb3d9S7DpzSRb6K1GwvYF8jUPUJVHt9gHuWkCpgEx1Why3VVaesD6fzP3SIgK3ZTCcO62SrhnL4vMLM8czSMzTzahW5WXHxFetmF6TxtR9C5BscikZkqlX+Ggprq3RsEyCJIbICY4nLAZp/uOb50Jqzrd73pWeMEAEjZ8jCHQuEPMcJUvu4F9AGzGZOoKZi24phxENaNp++RWwBO88p+fo=
  template:
    metadata:
      name: paperless-keycloak-config-secret
      namespace: paperless
