apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - postgres-sealed-secret.yaml
  - ../../base/
  - paperless-ingress.yaml

patches:
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: paperless-db-secret
              key: POSTGRES_USER
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: paperless-db-secret
              key: POSTGRES_PASSWORD
    target:
      group: apps
      version: v1
      kind: Deployment
      name: db
