apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-paperless-media
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: evora.lan
    path: "/export/paperless-media"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: media
  name: media
spec:
  volumeName: nfs-pv-paperless-media
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: ""
