apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: paperless
  namespace: paperless
spec:
  defaultBackend:
    service:
      name: webserver
      port:
        name: http
  ingressClassName: tailscale
  tls:
    - hosts:
        - paperless
