kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: keycloak-ssd-encrypted
provisioner: driver.longhorn.io
allowVolumeExpansion: true
parameters:
  numberOfReplicas: "1"
  staleReplicaTimeout: "2880" # 48 hours in minutes
  diskSelector: "ssd"
  allowVolumeCreation: "true"
  reclaimPolicy: "Retain"
  fromBackup: ""
  encrypted: "true"
  # global secret that contains the encryption key that will be used for all volumes
  csi.storage.k8s.io/provisioner-secret-name: "storage-class-luks-crypto"
  csi.storage.k8s.io/provisioner-secret-namespace: "keycloak"
  csi.storage.k8s.io/node-publish-secret-name: "storage-class-luks-crypto"
  csi.storage.k8s.io/node-publish-secret-namespace: "keycloak"
  csi.storage.k8s.io/node-stage-secret-name: "storage-class-luks-crypto"
  csi.storage.k8s.io/node-stage-secret-namespace: "keycloak"
  csi.storage.k8s.io/node-expand-secret-name: "storage-class-luks-crypto"
  csi.storage.k8s.io/node-expand-secret-namespace: "keycloak"
