apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - sealed-secret.yaml
  - encrypted-storage-class.yaml
  - ../../base
patches:
  - target:
      kind: Application
      name: keycloak-helm-chart
    patch: |-
      - op: merge
        path: /spec/source
        value:
          helm:
            valuesObject:
              global:
                defaultStorageClass: keycloak-encrypted 
              ingress:
                enabled: true
                ingressClassName: tailscale
                hostname: sso
                extraTls:
                  - hosts:
                    - sso


