apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - sealed-secret.yaml
  - encrypted-storage-class.yaml
  - ../../base

patchesStrategicMerge:
  - |-
    apiVersion: argoproj.io/v1alpha1
    kind: Application
    metadata:
      name: keycloak-helm-chart
      namespace: keycloak
    spec:
      source:
        helm:
          valuesObject:
            global:
              defaultStorageClass: keycloak-encrypted 
            ingress:
              enabled: true
              ingressClassName: tailscale
              hostname: sso
              extraTls:
                - hosts:
                  - sso
