apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - keycloak-sc.yaml
  - keycloak-config-sealed-secret.yaml
  - ../../base

patchesStrategicMerge:
  - |-
    apiVersion: argoproj.io/v1alpha1
    kind: Application
    metadata:
      name: keycloak-helm-chart
      namespace: keycloak
    spec:
      source:
        helm:
          valuesObject:
            production: true
            global:
              defaultStorageClass: keycloak-sc
            auth:
              adminUser: admin
              existingSecret: keycloak-config
              passwordSecretKey: admin-keycloak-password
            proxyHeaders: |
              X-Forwarded-Proto: https
              X-Forwarded-Host: $host
              X-Forwarded-Port: "443"
              X-Forwarded-For: $remote_addr
            ingress:
              enabled: true
              ingressClassName: tailscale
              hostname: sso.tail9a43.ts.net
              extraHosts:
                - name: sso
                  path: /
              extraTls:
                - hosts:
                  - sso
              annotations:
                tailscale.com/funnel: "true"
            postgresql:
              auth:
                existingSecret: keycloak-config
