apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - keycloak-sc.yaml
  - keycloak-config-sealed-secret.yaml
  - self-hosted-apps-realm-sealed-secret.yaml
  - ../../base

patchesStrategicMerge:
  - |-
    apiVersion: argoproj.io/v1alpha1
    kind: Application
    metadata:
      name: keycloak-helm-chart
      namespace: keycloak
    spec:
      source:
        helm:
          valuesObject:
            production: true
            global:
              defaultStorageClass: keycloak-sc
            auth:
              adminUser: admin
              existingSecret: keycloak-config
              passwordSecretKey: admin-keycloak-password
            proxy: edge
            ingress:
              enabled: true
              ingressClassName: tailscale
              hostname: sso.tail9a43.ts.net
              extraHosts:
                - name: sso
                  path: /
              extraTls:
                - hosts:
                  - sso
            postgresql:
              auth:
                existingSecret: keycloak-config
            extraStartupArgs: "-Dkeycloak.import=/opt/bitnami/keycloak/data/import/realm.json"
            extraVolumes:
              - name: realm-json
                secret:
                  secretName: self-hosted-apps-realm-secret
            extraVolumeMounts:
              - name: realm-json
                mountPath: /opt/bitnami/keycloak/data/import/
