apiVersion: batch/v1
kind: CronJob
metadata:
  name: actual-flow-import
  namespace: actual-budget
spec:
  # Run daily at 6PM (18:00)
  schedule: "0 18 * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: actual-flow-import
            image: node:24-alpine@sha256:931d7d57f8c1fd0e2179dbff7cc7da4c9dd100998bc2b32afc85142d8efbc213
            command:
            - /bin/sh
            - -c
            - |
              cd /tmp
              cp /config/config.json .
              npx @lunchflow/actual-flow import
            volumeMounts:
            - name: config
              mountPath: /config
              readOnly: true
          volumes:
          - name: config
            secret:
              secretName: actual-flow-config
