apiVersion: batch/v1
kind: CronJob
metadata:
  name: actual-flow-import
  namespace: actual-budget
spec:
  # Run daily at 6PM (18:00)
  schedule: "0 18 * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: actual-flow-import
            image: node:24-alpine@sha256:4f696fbf39f383c1e486030ba6b289a5d9af541642fc78ab197e584a113b9c03
            command:
            - /bin/sh
            - -c
            - |
              cd /tmp
              cp /config/config.json .
              npx @lunchflow/actual-flow import
            volumeMounts:
            - name: config
              mountPath: /config
              readOnly: true
          volumes:
          - name: config
            secret:
              secretName: actual-flow-config
