apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trilium-helm-chart
  namespace: trilium
spec:
  project: trilium
  source:
    repoURL: https://triliumnext.github.io/helm-charts
    targetRevision: 1.x
    chart: trilium
  destination:
    server: https://kubernetes.default.svc
    namespace: trilium
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
      - CreateNamespace=true
